#!/bin/busybox sh
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

modprobe applespi
modprobe apple-ibridge
modprobe apple-ib-tb
modprobe apple-ib-als

cryptsetup open $(findfs UUID=1d815ab8-5c0b-4eb3-89e1-4d16b69bfd29) root || exec sh
mount -o ro $(findfs UUID=ce6f4d7b-e8e6-4585-a687-988d7b5bf8ac) /mnt/root || exec sh

umount /dev
umount /sys
umount /proc

exec switch_root /mnt/root /sbin/init
