alias virtual="xfreerdp /u:foster /f /v:virtual"
alias virtualmon="xfreerdp /u:foster /size:1920x1080 /v:virtual"
alias minecraft="java -jar ~/.minecraft/Minecraft.jar"
alias technic="java -jar ~/.technic/launcher.jar"
alias fcc="env WINEPREFIX="/home/foster/.wine" wine C:\\\\windows\\\\command\\\\start.exe /Unix /home/foster/.wine/dosdevices/c:/users/Public/Desktop/FirstClass.lnk"
alias scsh="mosh -p 1024"
