#!/bin/sh
if [ "$#" -ne 2 ]; then
	echo "Usage: $0 <time> <priority>"
	echo
	echo "Time can be specified according to the specification in 'systemd.time(7)'."
	echo "Priority is the log levels as specified in 'journalctl(1)'."

	exit 1
fi

source /etc/default/logmail

journal=$(journalctl --since="$1" --priority="$2" --no-pager --quiet | grep -v '^-- No entries --$')
units=$(systemctl --state=failed --no-pager --no-legend)

message=""

if [ "${#journal}" -ne 0 ]; then
	message="$(printf "$message\nJournal Log\n-----------\n$journal\n")"
fi

if [ "${#units}" -ne 0 ]; then
	message="$(printf "$message\nFailed Units\n------------\n$units\n")"
fi

if [ "${#message}" -ne 0 ]; then
	message="$(printf "Details for $(hostname):\n$message")"

	echo "$message" | mail -s "$subject" "$mailto"
fi
