#!/bin/sh
# global settings
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

# desktop settings
bspc config border_width 2
bspc config window_gap 12

# rules
bspc rule -a qjackctl state=floating
bspc rule -a qsynth state=floating
bspc rule -a Google-chrome:crx_gaedmjdfmmahhbjefcbgaolhhanlaolb state=floating
