#!/bin/sh
# global settings
bspc config split_ratio 0.52
bspc config history_aware_focus true
bspc config focus_by_distance true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

# desktop settings
bspc config border_width 2
bspc config window_gap 12

# node settings
~/.config/bspwm/bspwmmon eDP1

# rules
bspc -a qjackctl state=floating
