#!/bin/sh
bspc config border_width 2
bspc config window_gap 12

bspc config top_padding 19

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config history_aware_focus true
bspc config focus_follows_pointer true

bspc monitor -d term www chat work school music games
